### ISSUE TITLE
simple get requests don't follow redirects

### ISSUE THREAD

**Issue by piedoom** [greyblake/crystal-cossack#9]
Hi - 
I'm having a bit of trouble using the simple get example listed.

```
response = Cossack.get("http://doomy.tumblr.com/api/read/json")
```

returns a status of 301.

However, this works correctly.

```
cossack = Cossack::Client.new do |client|
  # follow up to 10 redirections (by default 5)
  client.use Cossack::RedirectionMiddleware, limit: 10
end

return cossack.get("http://doomy.tumblr.com/api/read/json")
```

Is this intended?  I would like to use the simple `Cossack.get` static method as I don't need to configure anything, however it gives me a 301 instead of following the redirect.

**Comment by greyblake** [comment]
Hi.. Yes it's done by intention. Sorry, the only thing I can recommend is to create an instance of a client with middleware.

**Comment by piedoom** [comment]
Thanks for the response!
